

[program:backup]
command= bash -c '/path/to/backup_scripts/script.sh path/to/backup_scripts/config.yml && sleep 86400'
startsecs = 0
directory=/path/to/chakra-docker
user=user
autostart=true
autorestart=true
startretries=3

