location /_next/static {
    alias /home/ubuntu/chakra-docker/codebase/chakra-frontend/.next/static;
    add_header Cache-Control "public, max-age=3600, immutable";
}

location / {
    # Throttling for web socket URLs
    limit_req zone=chakra_zone burst=24 nodelay;

    # Reverse proxy the request to the upstream Daphne server
    proxy_pass          http://next;

    # These headers upgrade HTTP to WS
    proxy_http_version  1.1;
    proxy_set_header    Upgrade         $http_upgrade;
    proxy_set_header    Connection      "Upgrade";
}
