# The upstream Gunicorn component NGINX needs to connect to
upstream gunicorn {
    # Here internet-server automatically refers to the Internet site container
    server 127.0.0.1:8000; # Web port socket
}

# The upstream Daphne component NGINX needs to connect to
upstream daphne {
    # Here internet-server automatically refers to the Internet site container
    server 127.0.0.1:8001; # Web port socket
}

upstream next {
    server 127.0.0.1:3000;
}