# Use RabbitMQ from the Debian Linux project
FROM rabbitmq:management

# Add labels for metadata
LABEL maintainer="IMG, IIT Roorkee <https://img.channeli.in>"

# Install the health check script
COPY checkhealth.sh /usr/local/bin/checkhealth
